// Code generated by protoc-gen-go.
// source: wire/wire.proto
// DO NOT EDIT!

/*
Package wire is a generated protocol buffer package.

It is generated from these files:
	wire/wire.proto

It has these top-level messages:
	OpeningTx
	UpdateTx
	FollowOnTx
	ClosingTx
	Envelope
	Parcel
*/
package wire

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type OpeningTx struct {
	ChannelId  string   `protobuf:"bytes,1,opt,name=channel_id" json:"channel_id,omitempty"`
	Pubkeys    [][]byte `protobuf:"bytes,2,rep,name=pubkeys,proto3" json:"pubkeys,omitempty"`
	State      []byte   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	HoldPeriod uint64   `protobuf:"varint,4,opt,name=hold_period" json:"hold_period,omitempty"`
}

func (m *OpeningTx) Reset()                    { *m = OpeningTx{} }
func (m *OpeningTx) String() string            { return proto.CompactTextString(m) }
func (*OpeningTx) ProtoMessage()               {}
func (*OpeningTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type UpdateTx struct {
	ChannelId      string `protobuf:"bytes,1,opt,name=channel_id" json:"channel_id,omitempty"`
	SequenceNumber uint32 `protobuf:"varint,2,opt,name=sequence_number" json:"sequence_number,omitempty"`
	Fast           bool   `protobuf:"varint,3,opt,name=fast" json:"fast,omitempty"`
	State          []byte `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
}

func (m *UpdateTx) Reset()                    { *m = UpdateTx{} }
func (m *UpdateTx) String() string            { return proto.CompactTextString(m) }
func (*UpdateTx) ProtoMessage()               {}
func (*UpdateTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type FollowOnTx struct {
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id" json:"channel_id,omitempty"`
	State     []byte `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (m *FollowOnTx) Reset()                    { *m = FollowOnTx{} }
func (m *FollowOnTx) String() string            { return proto.CompactTextString(m) }
func (*FollowOnTx) ProtoMessage()               {}
func (*FollowOnTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ClosingTx struct {
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id" json:"channel_id,omitempty"`
}

func (m *ClosingTx) Reset()                    { *m = ClosingTx{} }
func (m *ClosingTx) String() string            { return proto.CompactTextString(m) }
func (*ClosingTx) ProtoMessage()               {}
func (*ClosingTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Envelope struct {
	Payload    []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signatures [][]byte `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
}

func (m *Envelope) Reset()                    { *m = Envelope{} }
func (m *Envelope) String() string            { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()               {}
func (*Envelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Parcel struct {
	Envelopes []*Envelope `protobuf:"bytes,1,rep,name=envelopes" json:"envelopes,omitempty"`
}

func (m *Parcel) Reset()                    { *m = Parcel{} }
func (m *Parcel) String() string            { return proto.CompactTextString(m) }
func (*Parcel) ProtoMessage()               {}
func (*Parcel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Parcel) GetEnvelopes() []*Envelope {
	if m != nil {
		return m.Envelopes
	}
	return nil
}

func init() {
	proto.RegisterType((*OpeningTx)(nil), "wire.OpeningTx")
	proto.RegisterType((*UpdateTx)(nil), "wire.UpdateTx")
	proto.RegisterType((*FollowOnTx)(nil), "wire.FollowOnTx")
	proto.RegisterType((*ClosingTx)(nil), "wire.ClosingTx")
	proto.RegisterType((*Envelope)(nil), "wire.Envelope")
	proto.RegisterType((*Parcel)(nil), "wire.Parcel")
}

var fileDescriptor0 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x4f, 0x3a, 0x31,
	0x10, 0xc5, 0x03, 0xec, 0x97, 0x2f, 0x3b, 0x20, 0x24, 0x8d, 0x87, 0xbd, 0xa8, 0x64, 0x2f, 0xee,
	0xc1, 0x40, 0xa2, 0x89, 0x77, 0xe3, 0x8f, 0xc4, 0x8b, 0x90, 0x46, 0xcf, 0xa4, 0xb0, 0x23, 0x34,
	0xd6, 0xb6, 0xb6, 0x5d, 0x91, 0xe8, 0x1f, 0x6f, 0xb7, 0xb0, 0x42, 0xf4, 0xc0, 0x65, 0x33, 0xf3,
	0x76, 0xfa, 0x3e, 0x2f, 0x33, 0xd0, 0x5b, 0x72, 0x83, 0xc3, 0xf2, 0x33, 0xd0, 0x46, 0x39, 0x45,
	0xa2, 0xb2, 0x4e, 0x3f, 0x21, 0x1e, 0x69, 0x94, 0x5c, 0xce, 0x1f, 0x3f, 0xc8, 0x11, 0xc0, 0x6c,
	0xc1, 0xa4, 0x44, 0x31, 0xe1, 0x79, 0x52, 0xeb, 0xd7, 0xb2, 0x98, 0xc6, 0x1b, 0xe5, 0x3e, 0x27,
	0x09, 0xfc, 0xd7, 0xc5, 0xf4, 0x05, 0x57, 0x36, 0xa9, 0xf7, 0x1b, 0x59, 0x87, 0x56, 0x2d, 0x39,
	0x84, 0x7f, 0xd6, 0x31, 0x87, 0x49, 0xc3, 0xbf, 0xe9, 0xd0, 0x75, 0x43, 0x4e, 0xa0, 0xbd, 0x50,
	0x22, 0x9f, 0x68, 0x34, 0x5c, 0xe5, 0x49, 0xe4, 0xff, 0x45, 0x14, 0x4a, 0x69, 0x1c, 0x94, 0xf4,
	0x0b, 0x5a, 0x4f, 0x3a, 0xf7, 0xa3, 0xfb, 0xd9, 0xa7, 0xd0, 0xb3, 0xf8, 0x56, 0xa0, 0x9c, 0xe1,
	0x44, 0x16, 0xaf, 0x53, 0x34, 0x3e, 0x43, 0x2d, 0x3b, 0xa0, 0xdd, 0x4a, 0x7e, 0x08, 0x2a, 0x21,
	0x10, 0x3d, 0x33, 0xeb, 0x42, 0x92, 0x16, 0x0d, 0xf5, 0x36, 0x5e, 0xb4, 0x13, 0x2f, 0xbd, 0x02,
	0xb8, 0x53, 0x42, 0xa8, 0xe5, 0x48, 0xee, 0xe7, 0xff, 0x58, 0xd4, 0x77, 0x2d, 0x86, 0xd0, 0xbd,
	0x66, 0x9e, 0x2d, 0x04, 0x73, 0x5c, 0xfd, 0xb5, 0xa9, 0xff, 0xb2, 0x49, 0x6f, 0xa0, 0x75, 0x2b,
	0xdf, 0x51, 0x28, 0x8d, 0x61, 0x9d, 0x6c, 0x25, 0x14, 0x5b, 0xe3, 0xca, 0x75, 0xae, 0x5b, 0x72,
	0x0c, 0x60, 0xf9, 0x5c, 0x32, 0x57, 0x18, 0xac, 0x76, 0xbd, 0xa3, 0xa4, 0x97, 0xd0, 0x1c, 0x33,
	0xe3, 0xb1, 0xe4, 0x0c, 0x62, 0xdc, 0xf8, 0x59, 0xef, 0xd2, 0xc8, 0xda, 0xe7, 0xdd, 0x41, 0x38,
	0x72, 0x85, 0xa1, 0xdb, 0x81, 0x69, 0x33, 0x5c, 0xfe, 0xe2, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x97,
	0xf8, 0xd7, 0x70, 0x0c, 0x02, 0x00, 0x00,
}
