// Code generated by protoc-gen-go.
// source: wire/wire.proto
// DO NOT EDIT!

/*
Package wire is a generated protocol buffer package.

It is generated from these files:
	wire/wire.proto

It has these top-level messages:
	OpeningTx
	UpdateTx
	FollowOnData
	Cancellation
	Envelope
*/
package wire

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Envelope_Type int32

const (
	Envelope_OpeningTx    Envelope_Type = 0
	Envelope_UpdateTx     Envelope_Type = 1
	Envelope_FollowOnData Envelope_Type = 2
	Envelope_Cancellation Envelope_Type = 3
)

var Envelope_Type_name = map[int32]string{
	0: "OpeningTx",
	1: "UpdateTx",
	2: "FollowOnData",
	3: "Cancellation",
}
var Envelope_Type_value = map[string]int32{
	"OpeningTx":    0,
	"UpdateTx":     1,
	"FollowOnData": 2,
	"Cancellation": 3,
}

func (x Envelope_Type) String() string {
	return proto.EnumName(Envelope_Type_name, int32(x))
}
func (Envelope_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type OpeningTx struct {
	ChannelId  string   `protobuf:"bytes,1,opt,name=channel_id" json:"channel_id,omitempty"`
	Pubkeys    [][]byte `protobuf:"bytes,2,rep,name=pubkeys,proto3" json:"pubkeys,omitempty"`
	State      []byte   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	HoldPeriod uint32   `protobuf:"varint,4,opt,name=hold_period" json:"hold_period,omitempty"`
}

func (m *OpeningTx) Reset()                    { *m = OpeningTx{} }
func (m *OpeningTx) String() string            { return proto.CompactTextString(m) }
func (*OpeningTx) ProtoMessage()               {}
func (*OpeningTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type UpdateTx struct {
	ChannelId      string `protobuf:"bytes,1,opt,name=channel_id" json:"channel_id,omitempty"`
	SequenceNumber uint32 `protobuf:"varint,2,opt,name=sequence_number" json:"sequence_number,omitempty"`
	Fast           bool   `protobuf:"varint,3,opt,name=fast" json:"fast,omitempty"`
	State          []byte `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
}

func (m *UpdateTx) Reset()                    { *m = UpdateTx{} }
func (m *UpdateTx) String() string            { return proto.CompactTextString(m) }
func (*UpdateTx) ProtoMessage()               {}
func (*UpdateTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type FollowOnData struct {
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id" json:"channel_id,omitempty"`
	State     []byte `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (m *FollowOnData) Reset()                    { *m = FollowOnData{} }
func (m *FollowOnData) String() string            { return proto.CompactTextString(m) }
func (*FollowOnData) ProtoMessage()               {}
func (*FollowOnData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Cancellation struct {
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id" json:"channel_id,omitempty"`
}

func (m *Cancellation) Reset()                    { *m = Cancellation{} }
func (m *Cancellation) String() string            { return proto.CompactTextString(m) }
func (*Cancellation) ProtoMessage()               {}
func (*Cancellation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Envelope struct {
	Type       Envelope_Type `protobuf:"varint,1,opt,name=type,enum=wire.Envelope_Type" json:"type,omitempty"`
	Payload    []byte        `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signatures [][]byte      `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty"`
}

func (m *Envelope) Reset()                    { *m = Envelope{} }
func (m *Envelope) String() string            { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()               {}
func (*Envelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*OpeningTx)(nil), "wire.OpeningTx")
	proto.RegisterType((*UpdateTx)(nil), "wire.UpdateTx")
	proto.RegisterType((*FollowOnData)(nil), "wire.FollowOnData")
	proto.RegisterType((*Cancellation)(nil), "wire.Cancellation")
	proto.RegisterType((*Envelope)(nil), "wire.Envelope")
	proto.RegisterEnum("wire.Envelope_Type", Envelope_Type_name, Envelope_Type_value)
}

var fileDescriptor0 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x53, 0xc2, 0x30,
	0x10, 0xb5, 0x50, 0x15, 0xd6, 0x02, 0x9d, 0xe8, 0xa1, 0x17, 0x95, 0xe9, 0x45, 0x2e, 0xe2, 0x8c,
	0xfe, 0x04, 0xfc, 0x18, 0x2f, 0xe2, 0x74, 0xf0, 0xcc, 0x04, 0xba, 0x42, 0xc7, 0x98, 0xc4, 0x26,
	0x15, 0x19, 0xfd, 0x5d, 0xfe, 0x3e, 0x93, 0x48, 0xa5, 0x9e, 0x7a, 0xe9, 0xec, 0xbe, 0xdd, 0xbe,
	0x7d, 0xbb, 0x2f, 0xd0, 0x5b, 0x65, 0x39, 0x5e, 0xd8, 0xcf, 0x50, 0xe6, 0x42, 0x0b, 0xe2, 0xdb,
	0x38, 0xfe, 0x84, 0xf6, 0x58, 0x22, 0xcf, 0xf8, 0x62, 0xf2, 0x41, 0x8e, 0x01, 0xe6, 0x4b, 0xca,
	0x39, 0xb2, 0x69, 0x96, 0x46, 0x5e, 0xdf, 0x1b, 0xb4, 0x93, 0xf6, 0x06, 0xb9, 0x4f, 0x49, 0x04,
	0xfb, 0xb2, 0x98, 0xbd, 0xe0, 0x5a, 0x45, 0x8d, 0x7e, 0x73, 0x10, 0x24, 0x65, 0x4a, 0x8e, 0x60,
	0x57, 0x69, 0xaa, 0x31, 0x6a, 0x9a, 0x7f, 0x82, 0xe4, 0x37, 0x21, 0xa7, 0x70, 0xb0, 0x14, 0x2c,
	0x9d, 0x4a, 0xcc, 0x33, 0x91, 0x46, 0xbe, 0xa9, 0x75, 0x12, 0xb0, 0xd0, 0xa3, 0x43, 0xe2, 0x2f,
	0x68, 0x3d, 0xc9, 0xd4, 0xb4, 0xd6, 0xcf, 0x3e, 0x83, 0x9e, 0xc2, 0xb7, 0x02, 0xf9, 0x1c, 0xa7,
	0xbc, 0x78, 0x9d, 0x61, 0x6e, 0x34, 0x58, 0xbe, 0x6e, 0x09, 0x3f, 0x38, 0x94, 0x10, 0xf0, 0x9f,
	0xa9, 0xd2, 0x4e, 0x49, 0x2b, 0x71, 0xf1, 0x56, 0x9e, 0x5f, 0x91, 0x17, 0x8f, 0x20, 0xb8, 0x15,
	0x8c, 0x89, 0xd5, 0x98, 0x5f, 0x53, 0x4d, 0xeb, 0x14, 0xfc, 0x91, 0x34, 0xaa, 0x24, 0xe7, 0x10,
	0x8c, 0xa8, 0x99, 0xce, 0x18, 0xd5, 0x99, 0xe0, 0x35, 0x24, 0xf1, 0xb7, 0x07, 0xad, 0x1b, 0xfe,
	0x8e, 0x4c, 0x48, 0x34, 0x3b, 0xf9, 0x7a, 0x2d, 0xd1, 0x75, 0x75, 0x2f, 0x0f, 0x87, 0xce, 0x9c,
	0xb2, 0x3a, 0x9c, 0x98, 0x52, 0xe2, 0x1a, 0xdc, 0xe1, 0xe9, 0x9a, 0x09, 0x9a, 0x6e, 0x86, 0x97,
	0x29, 0x39, 0x01, 0x50, 0xd9, 0x82, 0x53, 0x5d, 0xe4, 0xa8, 0xcc, 0xce, 0xd6, 0x95, 0x0a, 0x12,
	0xdf, 0x81, 0x6f, 0x79, 0x48, 0xa7, 0x62, 0x73, 0xb8, 0x43, 0x82, 0xed, 0xe1, 0x43, 0x8f, 0x84,
	0xff, 0x0f, 0x11, 0x36, 0x2c, 0x52, 0xdd, 0x2a, 0x6c, 0xce, 0xf6, 0xdc, 0xa3, 0xb9, 0xfa, 0x09,
	0x00, 0x00, 0xff, 0xff, 0xe5, 0xab, 0xac, 0x4e, 0x47, 0x02, 0x00, 0x00,
}
